# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpolgamma <- function(n, b, mu) {
    .Call('_poispolgamma_rpolgamma', PACKAGE = 'poispolgamma', n, b, mu)
}

